version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  jest:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
  eslint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lint
workflows:
  build-and-test:
    jobs:
      - jest
      - eslint
